openapi: 3.0.3
info:
  title: AI Lesson Generator API
  description: API for auto-generating audio/video lessons from text
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Local server
paths:
  /api/auth/register:
    post:
      summary: Register a new user
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: teacher@example.com
                username:
                  type: string
                  example: Teacher Name
                password:
                  type: string
                  example: password123
              required:
                - email
                - username
                - password
      responses:
        '201':
          description: User registered successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Đăng ký thành công
        '400':
          description: Email already exists
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Email đã được sử dụng
        '500':
          description: Server error
  /api/auth/login:
    post:
      summary: Login user
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  example: Teacher Name
                password:
                  type: string
                  example: password123
              required:
                - username
                - password
      responses:
        '200':
          description: Login successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
                  message:
                    type: string
                    example: Đăng nhập thành công
        '400':
          description: Invalid credentials
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Tên người dùng hoặc mật khẩu không đúng
        '500':
          description: Server error
  /api/lessons:
    post:
      summary: Create a new lesson
      tags:
        - Lessons
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                title:
                  type: string
                  example: Bài giảng Toán học
                text_content:
                  type: string
                  example: Đây là nội dung bài giảng...
                language:
                  type: string
                  example: vi
                voice_id:
                  type: string
                  example: voice_id_here
                file:
                  type: string
                  format: binary
              required:
                - title
                - voice_id
      responses:
        '201':
          description: Lesson created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Bài giảng đã được tạo, đang xử lý
                  lesson:
                    type: object
                    properties:
                      id:
                        type: string
                      title:
                        type: string
        '500':
          description: Server error
    get:
      summary: Get all lessons
      tags:
        - Lessons
      security:
        - bearerAuth: []
      responses:
        '200':
          description: List of lessons
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    title:
                      type: string
                    status:
                      type: string
                      enum: [uploaded, processing, failed, completed]
        '500':
          description: Server error
  /api/lessons/{id}/status:
    get:
      summary: Get lesson status
      tags:
        - Lessons
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: Lesson ID
      responses:
        '200':
          description: Lesson status
          content:
            application/json:
              schema:
                type: object
                properties:
                  lesson:
                    type: object
                    properties:
                      id:
                        type: string
                      title:
                        type: string
                      status:
                        type: string
                        enum: [uploaded, processing, failed, completed]
        '404':
          description: Lesson not found
        '403':
          description: Unauthorized access
        '500':
          description: Server error
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT